=== JoHaHu/MolSim/src/lib/simulator/io/xml_reader/SimulationInputSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Define the root element -->
    <xs:element name="Data">
        <xs:complexType>
            <xs:sequence>
                <!-- Header element with attributes globally defined for the whole simulation -->
                <xs:element name="header">
                    <xs:complexType>
                        <xs:attribute name="base_name" type="xs:string" use="required"/>
                        <xs:attribute name="t_end" type="xs:double" use="required"/>
                        <xs:attribute name="output_frequency" type="xs:double" use="required"/>
                        <xs:attribute name="output_file_name" type="xs:string" use="required"/>
                        <xs:attribute name="seed" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>

                <!-- Choice of simulation type -->
                <xs:choice>
                    <!-- Gravity simulation -->
                    <xs:element name="gravity">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="total_bodies" type="xs:double"/>
                                <xs:element name="celestial_body" type="celestial_body" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <!-- Lennard-Jones simulation -->
                    <xs:element name="lennard_jones">
                        <xs:complexType>
                            <xs:sequence>
                                <!-- Constants that are set globally for the simulation and not specific to any cuboid or disc -->
                                <xs:element name="settings">
                                    <xs:complexType>
                                        <xs:attribute name="delta_t" type="xs:double" use="required"/>
                                        <xs:attribute name="sigma" type="xs:double" use="required"/>
                                        <xs:attribute name="epsilon" type="xs:double" use="required"/>
                                        <xs:attribute name="mass_m" type="xs:double" use="required"/>
                                        <xs:attribute name="distance_h" type="xs:double" use="required"/>
                                        <xs:attribute name="brown_motion" type="xs:double" use="required"/>
                                    </xs:complexType>
                                </xs:element>

                                <!-- Choice between cuboids and discs -->
                                <xs:choice>
                                    <xs:element name="cuboids">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="Cuboid" type="cuboid" maxOccurs="unbounded"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="discs">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="Disc" type="disc" maxOccurs="unbounded"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:choice>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Definition of intArray as an array of 3 integers -->
    <xs:complexType name="double_array">
        <xs:sequence>
            <xs:element name="value" type="xs:double" maxOccurs="3" minOccurs="3"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definition of celestial body described by 2 integer arrays and 1 double -->
    <xs:complexType name="celestial_body">
        <xs:sequence>
            <!-- Disc description parameters -->
            <xs:element name="coordinate" type="double_array"/>
            <xs:element name="velocity" type="double_array"/>
            <xs:element name="mass" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definition of cuboid described by 3 integer arrays -->
    <xs:complexType name="cuboid">
        <xs:sequence>
            <!-- Cuboid description parameters -->
            <xs:element name="coordinate"
                        type="double_array"/>  <!-- coordinate is defined as the lower left front particle coordinate -->
            <xs:element name="particle_counts" type="double_array"/>
            <xs:element name="velocity" type="double_array"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definition of disc described by 2 integer arrays and 1 double -->
    <xs:complexType name="disc">
        <xs:sequence>
            <!-- Disc description parameters -->
            <xs:element name="coordinate"
                        type="double_array"/>  <!-- coordinate is defined as the center particle coordinate -->
            <xs:element name="velocity" type="double_array"/>
            <xs:element name="radius"
                        type="xs:int"/>  <!-- radius is defined as the amount of particle along the radius of the disc -->
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== JoHaHu/MolSim/input/eingabe-collision-ws.xml
<?xml version="1.0" encoding="UTF-8"?>

<Data xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
      xs:noNamespaceSchemaLocation="../src/lib/simulator/io/xml_reader/SimulationInputSchema.xsd">

    <header base_name="Collision of two bodies" output_file_name="collision_simulation" output_frequency="0" t_end="5"
            seed="1234"/>

    <vector>
        true
    </vector>

    <lennard_jones>
        <settings delta_t="0.0002" sigma="1" epsilon="5" mass_m="1" distance_h="1.1225" brown_motion="0.1"
                  cutoff_radius="3"/>
        <cuboids>
            <Cuboid>
                <coordinate>
                    <value>0</value>
                    <value>0</value>
                    <value>0</value>
                </coordinate>
                <particle_counts>
                    <value>40</value>
                    <value>8</value>
                    <value>1</value>
                </particle_counts>
                <velocity>
                    <value>0</value>
                    <value>0</value>
                    <value>0</value>
                </velocity>
            </Cuboid>
            <Cuboid>
                <coordinate>
                    <value>15</value>
                    <value>15</value>
                    <value>0</value>
                </coordinate>
                <particle_counts>
                    <value>8</value>
                    <value>8</value>
                    <value>1</value>
                </particle_counts>
                <velocity>
                    <value>0</value>
                    <value>-10</value>
                    <value>0</value>
                </velocity>
            </Cuboid>
        </cuboids>
    </lennard_jones>
</Data>

=== JoHaHu/MolSim/input/eingabe-disc-ws3.xml
<?xml version="1.0" encoding="UTF-8"?>

<Data xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
      xs:noNamespaceSchemaLocation="../src/lib/simulator/io/xml_reader/SimulationInputSchema.xsd">

    <header base_name="Simulation of a falling drop - Wall" output_file_name="falling_drop_simulation"
            output_frequency="100" t_end="10" seed="1234"/>

    <linked_cells>
        <domain_size>
            <value>0</value>
            <value>180</value>
            <value>90</value>
        </domain_size>
    </linked_cells>

    <lennard_jones>
        <settings delta_t="0.00005" sigma="1" epsilon="5" mass_m="1" distance_h="1.1225" brown_motion="0.1" cutoff_radius="0"/>
        <discs>
            <Disc>
                <coordinate>
                    <value>60</value>
                    <value>25</value>
                    <value>0</value>
                </coordinate>
                <velocity>
                    <value>0</value>
                    <value>-10</value>
                    <value>0</value>
                </velocity>
                <radius>15</radius>
            </Disc>
        </discs>
    </lennard_jones>
</Data>
